#!/usr/bin/env python3
"""Regenerate assets/js/gpus.js from data/hashrate-no-gpus-*.json (stdlib only).

Usage (from the repo root):
    python3 apps/web/scripts/gen_gpus.py data/hashrate-no-gpus-2026-10-03.json

The site loads GPU data as a plain script (not fetch) so it also works when
the HTML is opened straight from disk.
"""
import json
import re
import sys
from pathlib import Path

src = Path(sys.argv[1] if len(sys.argv) > 1 else "data/hashrate-no-gpus-2026-10-03.json")
date = re.search(r"(\d{4}-\d{2}-\d{2})", src.name)
rows = json.loads(src.read_text())
PRO = re.compile(r"^(CMP |RTX PRO |RTX A\d|TITAN|P10\d)")

out = []
for r in rows:
    # Watts are approximate: hashrate.no's revenue minus profit at $0.10/kWh.
    watts = round((r["rev24"] - r["profit24"]) / 0.10 / 24 * 1000 / 5) * 5
    group = "Pro & mining cards" if PRO.match(r["name"]) else r["brand"]
    out.append({
        "name": r["name"],
        "brand": r["brand"],
        "group": group,
        "coin": r["topRevCoin"],
        "rev": r["topRev24"],
        "w": max(watts, 0),
    })
out.sort(key=lambda g: -g["rev"])

dest = Path(__file__).resolve().parent.parent / "assets" / "js" / "gpus.js"
lines = [
    "// Generated by apps/web/scripts/gen_gpus.py. Do not edit by hand.",
    f"// Source: hashrate.no/gpus, fetched {date.group(1) if date else 'unknown'}. rev = 24h USD revenue on the card's best coin,",
    "// before electricity. w = approximate watts (hashrate.no revenue minus profit at $0.10/kWh).",
    f"window.GPU_DATA_DATE = \"{date.group(1) if date else ''}\";",
    "window.GPUS = [",
]
lines += ["  " + json.dumps(g, separators=(", ", ": ")) + "," for g in out]
lines.append("];")
dest.write_text("\n".join(lines) + "\n")
print(f"wrote {len(out)} GPUs to {dest}")
