#!/usr/bin/env python3
"""Regenerate assets/js/gpus.js from data/hashrate-no-gpus-*.json (stdlib only).

Usage (from the repo root):
    python3 apps/web/scripts/gen_gpus.py data/hashrate-no-gpus-2026-10-03.json

The site loads GPU data as a plain script (not fetch) so it also works when
the HTML is opened straight from disk.

hashrate.no only measures three laptop GPUs. Every other laptop GPU is
estimated from the desktop card with the same or nearest chip, scaled down for
laptop power limits (LAPTOPS below). Those rows carry "est": true and the site
labels them as estimates.
"""
import json
import re
import sys
from pathlib import Path

src = Path(sys.argv[1] if len(sys.argv) > 1 else "data/hashrate-no-gpus-2026-10-03.json")
date = re.search(r"(\d{4}-\d{2}-\d{2})", src.name)
rows = json.loads(src.read_text())
PRO = re.compile(r"^(CMP |RTX PRO |RTX A\d|TITAN|P10\d)")

# (laptop name, desktop reference on hashrate.no, factor, approx. mining watts)
# Factors: the measured laptops run at 0.72-0.76x their desktop sibling with the
# same chip (3070/3070 Ti) or about 1.0x when the laptop chip is the bigger one
# (3060). Cut-down laptop chips are scaled by core count on top of that.
LAPTOPS = [
    ("RTX 5090 Laptop", "RTX 5080", 0.72, 130),
    ("RTX 5080 Laptop", "RTX 5070 Ti", 0.64, 130),
    ("RTX 5070 Ti Laptop", "RTX 5070", 0.72, 115),
    ("RTX 5070 Laptop", "RTX 5060 Ti 16GB", 0.72, 95),
    ("RTX 5060 Laptop", "RTX 5060", 0.68, 95),
    ("RTX 5050 Laptop", "RTX 5050", 0.75, 80),
    ("RTX 4090 Laptop", "RTX 4080", 0.72, 130),
    ("RTX 4080 Laptop", "RTX 4070 Ti", 0.70, 130),
    ("RTX 4070 Laptop", "RTX 4060 Ti 16GB", 0.78, 95),
    ("RTX 4060 Laptop", "RTX 4060", 0.85, 95),
    ("RTX 4050 Laptop", "RTX 4060", 0.66, 80),
    ("RTX 3080 Ti Laptop", "RTX 3070 Ti Laptop", 1.15, 130),
    ("RTX 3080 Laptop", "RTX 3070 Ti Laptop", 1.0, 130),
    ("RTX 3050 Ti Laptop", "RTX 3050 8GB", 0.62, 65),
    ("RTX 3050 Laptop", "RTX 3050 8GB", 0.52, 65),
    ("RTX 2080 Super Laptop", "RTX 2080", 0.74, 120),
    ("RTX 2080 Laptop", "RTX 2080", 0.70, 120),
    ("RTX 2070 Super Laptop", "RTX 2070", 0.80, 95),
    ("RTX 2070 Laptop", "RTX 2070", 0.75, 95),
    ("RTX 2060 Laptop", "RTX 2060", 0.75, 75),
    ("GTX 1660 Ti Laptop", "GTX 1660 Ti", 0.85, 65),
    ("GTX 1650 Ti Laptop", "GTX 1660 Ti", 0.48, 45),
    ("GTX 1650 Laptop", "GTX 1660 Ti", 0.42, 45),
    ("RX 7900M", "RX 7900 GRE", 0.72, 150),
    ("RX 7700S", "RX 7600", 0.85, 85),
    ("RX 7600M XT", "RX 7600", 0.85, 100),
    ("RX 7600S", "RX 7600", 0.75, 75),
    ("RX 7600M", "RX 7600", 0.72, 75),
    ("RX 6850M XT", "RX 6700 XT", 0.88, 140),
    ("RX 6800M", "RX 6700 XT", 0.85, 120),
    ("RX 6700M", "RX 6700 XT", 0.72, 110),
    ("RX 6650M", "RX 6600", 0.90, 100),
    ("RX 6600M", "RX 6600", 0.85, 85),
    ("RX 6550M", "RX 6500 XT", 0.85, 65),
    ("RX 6500M", "RX 6500 XT", 0.75, 45),
    ("RX 5700M", "RX 5700", 0.75, 100),
    ("RX 5600M", "RX 5600 XT", 0.65, 60),
    ("RX 5500M", "RX 5500 XT", 0.72, 70),
    ("Arc A770M", "Arc A770", 0.70, 100),
    ("Arc A730M", "Arc A750", 0.60, 70),
    ("Arc A550M", "Arc A750", 0.35, 50),
    ("Arc A370M", "Arc A750", 0.18, 30),
]

out = []
by_name = {}
for r in rows:
    # Watts are approximate: hashrate.no's revenue minus profit at $0.10/kWh.
    watts = round((r["rev24"] - r["profit24"]) / 0.10 / 24 * 1000 / 5) * 5
    laptop = "Laptop" in r["name"]
    group = "Laptops" if laptop else "Workstation & mining cards" if PRO.match(r["name"]) else r["brand"]
    g = {
        "name": r["name"],
        "brand": r["brand"],
        "group": group,
        "coin": r["topRevCoin"],
        "rev": r["topRev24"],
        "w": max(watts, 0),
    }
    by_name[g["name"]] = g
    out.append(g)

for name, ref, factor, watts in LAPTOPS:
    base = by_name[ref]
    out.append({
        "name": name,
        "brand": "AMD" if name.startswith("RX") else "Intel" if name.startswith("Arc") else "NVIDIA",
        "group": "Laptops",
        "coin": base["coin"],
        "rev": round(base["rev"] * factor, 2),
        "w": watts,
        "est": True,
    })
out.sort(key=lambda g: -g["rev"])

dest = Path(__file__).resolve().parent.parent / "assets" / "js" / "gpus.js"
lines = [
    "// Generated by apps/web/scripts/gen_gpus.py. Do not edit by hand.",
    f"// Source: hashrate.no/gpus, fetched {date.group(1) if date else 'unknown'}. rev = 24h USD revenue on the card's best coin,",
    "// before electricity. w = approximate watts (hashrate.no revenue minus profit at $0.10/kWh).",
    "// est = laptop GPU estimated from its desktop sibling (hashrate.no measures only three laptops).",
    f"window.GPU_DATA_DATE = \"{date.group(1) if date else ''}\";",
    "window.GPUS = [",
]
lines += ["  " + json.dumps(g, separators=(", ", ": ")) + "," for g in out]
lines.append("];")
dest.write_text("\n".join(lines) + "\n")
print(f"wrote {len(out)} GPUs ({sum(1 for g in out if g['group'] == 'Laptops')} laptops) to {dest}")
